### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

### ISSUE THREAD

**Issue by JeffffffFu** [lxuechen/private-transformers#37] opened 2023-06-14 14:08 UTC
When I run private-transformers-main\private-transformers-main\examples\image_classification\main.py
and choose "cifar100" datasets，i get the error as follows:
![image](https://github.com/lxuechen/private-transformers/assets/42458424/1c965bd2-5e6c-4a98-99bd-404767bfb5d2)

**Comment by lxuechen** [comment] 2023-06-14 18:19
Hi, thanks for your interest! This error is usually caused by index out of bounds. Could you check if your code runs with non-private training and the labels are integers in the appropriate range?

**Comment by JeffffffFu** [comment] 2023-06-15 02:25
Thanks for your reply. First, I can run the code in CIFRA10 with private training. I follow your suggestion, and I can not run the code in CIFRA100 with non-private training, i.e. I delete the "privacy_engine.attach(optimizer)". I get the same error as above. I also print the label as follows:
![image](https://github.com/lxuechen/private-transformers/assets/42458424/56722652-1493-4a04-a0b1-0b7d94e5af73)
Thanks!

**Comment by lxuechen** [comment] 2023-06-15 03:23
> Thanks for your reply. First, I can run the code in CIFRA10 with private training. I follow your suggestion, and I can not run the code in CIFRA100 with non-private training, i.e. I delete the "privacy_engine.attach(optimizer)". I get the same error as above. I also print the label as follows: ![image](https://user-images.githubusercontent.com/42458424/245975465-56722652-1493-4a04-a0b1-0b7d94e5af73.png) Thanks!

This issue doesn't seem to be caused by the privacy engine but rather a mismatch between your logit tensor and labels. I'm closing this issue now.

Can you check if your predicted logits tensor has size (batch_size, 100)? You need 100 because for CIFAR-100, you're predicting 100 classes.

**Closed as completed by lxuechen** 2023-06-15 03:23 UTC
